---
- name: Deploy conf files from templates
  template: src={{ item.src }} dest={{ item.dest }} mode=0640 owner=keystone group=root
  with_items:
    - { src: 'keystone.conf.j2', dest: '/etc/keystone/keystone.conf' }
    - { src: 'wsgi-keystone.conf.j2', dest: '/etc/apache2/sites-available/keystone.conf' }

- name: Create keystone database
  mysql_db:
    name: keystone
    state: present

- name: Create keystone DB user
  mysql_user:
    name: keystone
    password: '{{ dbpass_keystone }}'
    priv: 'keystone.*:ALL,GRANT'
    state: present
 
- name: Create keystone tables in DB
  command: keystone-manage db_sync
  become: true
  become_user: keystone

- name: Initialize fernet tokens
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone

- name: Initialize fernet tokens
  command: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone


- name: Service http
  service: name=httpd enabled=yes state=restarted

- name: Service http wait for start
  wait_for: host={{ ks_mysql_host }} port=35357

- name: Bootstrap keystone admin and endpoint
  command: |
     keystone-manage bootstrap \
     --bootstrap-password {{ ks_auth_admin_password }} \
     --bootstrap-region-id {{ ks_service_region }} \
     --bootstrap-admin-url https://{{ ks_host }}:35357/v3 \
     --bootstrap-public-url https://{{ ks_host }}:5000/v3 \
     --bootstrap-internal-url https://{{ ks_host }}:5000/v3
  register: add_service
  until: add_service|success
  retries: 3
  delay: 5
