---
- name: Install packages keystone and mod-wsgi
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - keystone
    - libapache2-mod-wsgi

- name: Install cjose and mod_auth_openidc
  apt: deb={{ item }}
  with_items:
    - '{{ url_cjose }}'
    - '{{ url_oidc }}'

