---
- name: Install epel and centos-release-openstack-mitaka
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - epel-release
    - centos-release-openstack-mitaka

- name: Install packages
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - bind-utils
    - chrony
    - gcc
    - git
    - httpd
    - mod_wsgi
    - openstack-keystone
    - python-devel
    - python-memcached
    - python-openstackclient
    - python-pip
    - rabbitmq-server
    - wget

- name: Install mod_auth_openidc
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - https://github.com/pingidentity/mod_auth_openidc/releases/download/v1.8.10.1/mod_auth_openidc-1.8.10.1-1.el7.centos.x86_64.rpm